### ISSUE TITLE
ERROR: "server:prod" exited with 1.

### ISSUE THREAD

**Issue by afiqmuzaffar** [muratyaman/holland-codes-onet-careers-api#9]
> **npm run prod**

```
> holland-codes-onet-careers-api@1.0.0 prod
> NODE_ENV=production npm-run-all clean build server:prod


> holland-codes-onet-careers-api@1.0.0 clean
> rimraf dist


> holland-codes-onet-careers-api@1.0.0 build
> babel ./src --out-dir dist

Successfully compiled 8 files with Babel (556ms).

> holland-codes-onet-careers-api@1.0.0 server:prod
> node ./dist/index.js

/home/muzaffar/Downloads/m/worked/holland-codes-onet-careers-api-master/dist/utils.js:13
  var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(array, callback) {
                                             ^

ReferenceError: regeneratorRuntime is not defined
    at /home/muzaffar/Downloads/m/worked/holland-codes-onet-careers-api-master/dist/utils.js:13:46
    at Object.<anonymous> (/home/muzaffar/Downloads/m/worked/holland-codes-onet-careers-api-master/dist/utils.js:46:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/home/muzaffar/Downloads/m/worked/holland-codes-onet-careers-api-master/dist/HttpRoutes.js:12:14)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
ERROR: "server:prod" exited with 1.
```

**Comment by afiqmuzaffar** [comment]
Good day Sir @muratyaman , I'm interested to run this repo by running career api. I did followed requirement in _package.json_ and encountered error. How can I solve this Sir? Thank you in advance.

**Comment by muratyaman** [comment]
please check solution 1 on this URL:

https://flutterq.com/referenceerror-regeneratorruntime-is-not-defined-in-babel-7/
